<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Chicken</name>
   <tag></tag>
   <elementGuidId>f9481ce7-0889-41c6-a980-e3ee7a86cf0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='petAllergicTo']/div/div[3]/label/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Chicken&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa6f72ab-e4bb-463f-88f8-5c846bd36bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nutrition_form_block--radio-text</value>
      <webElementGuid>5ec0ffd6-0170-465e-8960-945d6b13821e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Chicken
                                                </value>
      <webElementGuid>8688b228-ee8d-4ed6-87c0-741dbb8e0c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;petAllergicTo&quot;)/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;position-relative col-6 align-self-center&quot;]/label[@class=&quot;nutrition_form_block--radio_label quizfullwidth&quot;]/div[@class=&quot;nutrition_form_block--radio_each quizshortheight&quot;]/div[@class=&quot;nutrition_form_block--radio-text&quot;]</value>
      <webElementGuid>913fbe6b-df10-4465-b5d3-935311937353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='petAllergicTo']/div/div[3]/label/div/div</value>
      <webElementGuid>b941797e-b27e-44dd-bafb-aff8e039d628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pork'])[1]/following::div[3]</value>
      <webElementGuid>818b2ef9-a3c5-4a09-83af-bf26db758a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None! All are OK'])[1]/following::div[6]</value>
      <webElementGuid>988e66fd-e661-4b40-92b2-7fc425feec79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turkey'])[1]/preceding::div[1]</value>
      <webElementGuid>3e623f1d-c0f5-41f2-a041-0353623f1abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beef'])[1]/preceding::div[4]</value>
      <webElementGuid>09ca74dc-6b29-4edc-a5a0-5c55add1deb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chicken']/parent::*</value>
      <webElementGuid>8c1f2e80-529e-47c8-83dd-834c9201643c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[3]/div/div/div[3]/label/div/div</value>
      <webElementGuid>666226ff-651c-4a25-9e93-446a61966821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                                    Chicken
                                                ' or . = '
                                                    Chicken
                                                ')]</value>
      <webElementGuid>890c62ca-3b06-4d53-9575-e81857007827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
