<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Moderate</name>
   <tag></tag>
   <elementGuidId>f628ad41-fdfc-42f5-ad65-b0a72231f3a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='petActivityLevel']/div/label[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Moderate&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a1e5379-8adf-4ba2-a69c-940a44709ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nutrition_form_block--radio-text quizactivitybutton</value>
      <webElementGuid>509fc361-66e4-4e92-81d1-f1dcbd2cec14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Moderate
                                            </value>
      <webElementGuid>d4f556d8-a7a1-4069-8c95-a01f533b18f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;petActivityLevel&quot;)/div[@class=&quot;justify-content-center&quot;]/label[@class=&quot;align-self-center nutrition_form_block--radio_label quizfullwidth&quot;]/div[@class=&quot;nutrition_form_block--radio_each quizbodybuttons&quot;]/div[@class=&quot;nutrition_form_block--radio-text quizactivitybutton&quot;]</value>
      <webElementGuid>10cb7f63-7cbf-4ac6-b2a8-24ec3fd7c9b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='petActivityLevel']/div/label[2]/div/div</value>
      <webElementGuid>074fc6a4-525e-4ee6-ba5a-690a01dd518a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short walks and sleeps most of the day.'])[1]/following::div[2]</value>
      <webElementGuid>aef21b53-b927-4338-a835-8e8ce5c7b092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Light'])[1]/following::div[3]</value>
      <webElementGuid>6bc9378c-c8a0-4526-9917-47f1c129ee4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular walks and daily playtime (best for most adult dogs).'])[1]/preceding::div[1]</value>
      <webElementGuid>9d6af93f-f15f-48ee-81a5-9ad80c39f5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[1]/preceding::div[2]</value>
      <webElementGuid>b579603d-765f-45bd-ab90-c7f1a1953a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Moderate']/parent::*</value>
      <webElementGuid>6fb7b242-3ea9-49c3-a65c-0e8c0d40de37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/label[2]/div/div</value>
      <webElementGuid>3348465a-9fc2-49c4-be90-2bf44be306f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                                Moderate
                                            ' or . = '
                                                Moderate
                                            ')]</value>
      <webElementGuid>ee7e0721-6852-4b51-8441-5ad69ea27c17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
