<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_petUserName</name>
   <tag></tag>
   <elementGuidId>a380318b-af69-45a2-937f-4b9de8257f61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#petUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='petUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Your first name here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c26085e2-ca34-4ee3-b155-160b61d07408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05aac2ab-12a5-44de-bc4c-64572257c88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-invalid</value>
      <webElementGuid>91568dbe-b32a-4b5a-8244-fc75fd158b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your first name here</value>
      <webElementGuid>684c8806-6650-4b2e-be8e-c540a4319897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>petUserName</value>
      <webElementGuid>e8fd70aa-00d3-49f9-8b56-17d0e506eb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_nutritionplanner_petUserName</value>
      <webElementGuid>aa6f3807-cf4c-4743-bac5-46a3ccb2b4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c8eb9dc-8fbf-4062-9606-8c2a5d4fa76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your first name here</value>
      <webElementGuid>d6f653ff-2745-4e1c-9f1b-9e9de89ae583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;petUserName&quot;)</value>
      <webElementGuid>3cfbaf30-f660-4a57-bacc-dfd6cda962f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='petUserName']</value>
      <webElementGuid>3c20ea27-be5f-4b4f-ad75-b0482d7149d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userEmailTab']/div[2]/input</value>
      <webElementGuid>109b4124-b712-43db-96ce-32f51a90be71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/input</value>
      <webElementGuid>4c9f976f-9d5b-42df-a0d6-411d3083a1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Your first name here' and @id = 'petUserName' and @name = 'dwfrm_nutritionplanner_petUserName']</value>
      <webElementGuid>66c7f58c-9b5d-46f1-9af6-a0ffe412fea0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
