<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight_petWeight</name>
   <tag></tag>
   <elementGuidId>4c14d33a-a8fc-4e4d-bda9-ee70dc869538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#petWeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='petWeight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter weight in pounds&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e1729cb-8cb9-47cc-a609-8fcefa33f2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text petWeight</value>
      <webElementGuid>4a81c75f-1d7d-46ad-98fb-9772bcc2f1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2fe3e5fd-3419-45bc-9a6d-ad69e0fb3a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a0f02a08-d0b2-4e0e-9212-a532fdd2e910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>58b1451c-8559-4d1d-b10b-b24a35e894ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>192ade1e-65fc-4b61-9879-eb07f3468f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>01aad57f-537f-487f-9ce2-d0d73098b757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>petWeight</value>
      <webElementGuid>d1680199-4b21-45d5-962f-158f653d32e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter weight in pounds</value>
      <webElementGuid>16747440-a83b-4397-8877-dc2d859b233e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_nutritionplanner_petWeight</value>
      <webElementGuid>f1c88052-0b53-4abf-9245-38b263dbdffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e367548-671b-423a-9596-0275e16df343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter weight in pounds</value>
      <webElementGuid>16011887-eb38-4311-8e13-dc990d37f9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;petWeight&quot;)</value>
      <webElementGuid>6d7e2b96-776e-4cd8-86ef-9472a7bc5816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='petWeight']</value>
      <webElementGuid>fd8b6409-5438-4e0f-93d7-645ed9bbb644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='petWeightTab']/div[2]/div/input</value>
      <webElementGuid>75a83e11-3618-49ff-b684-dab27486e4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>3420b2b7-fc7b-4935-bb4b-265b793db05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'petWeight' and @placeholder = 'Enter weight in pounds' and @name = 'dwfrm_nutritionplanner_petWeight']</value>
      <webElementGuid>bf2f4a7a-31bc-442e-8883-2e3a986697c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
