<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_petUserEmail</name>
   <tag></tag>
   <elementGuidId>de5e818d-eb0f-4a0e-97a9-105adcfbd73d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#petUserEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='petUserEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Your email here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04b7524b-9d30-4b17-bd92-519a9b886fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>22c30fed-5b9f-4836-9f6b-9111f9414c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-invalid error</value>
      <webElementGuid>34941a2e-4e8f-4f79-aa69-2b3b5f4c070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your email here</value>
      <webElementGuid>f565d554-6f43-45c3-b391-bfbec41fa25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>petUserEmail</value>
      <webElementGuid>3a6f4ec3-5161-4ab7-a5a8-d761c8abe3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_nutritionplanner_petUserEmail</value>
      <webElementGuid>afdb0885-0938-4702-8967-3a4a6927959c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cff684dd-f60d-4587-a67f-5462b845ef79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a01d1346-8e76-4987-bd80-b477a9b550ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\w.-]+@[\w.-]+\.[\w]{2,6}$</value>
      <webElementGuid>827d52ca-6fc2-4f8a-b2cd-67eecc2b185c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener</name>
      <type>Main</type>
      <value>klaviyo</value>
      <webElementGuid>e6d49564-9818-46ad-aca5-be54e11cc867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your email here</value>
      <webElementGuid>7f65cf00-b878-4383-97a5-72a5fa2de59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cffc9a5b-2b53-464f-9646-72ebe9415eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;petUserEmail&quot;)</value>
      <webElementGuid>1c748ac5-9326-46e1-873a-f218802052d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='petUserEmail']</value>
      <webElementGuid>19050d65-de2a-4338-8e4f-caac06ee76e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userEmailTab']/div[4]/input</value>
      <webElementGuid>43b12721-f701-4af7-98ad-aa5df0efca2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[4]/input</value>
      <webElementGuid>518a0a2e-ba13-4030-94b1-7fa501f1c551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Your email here' and @id = 'petUserEmail' and @name = 'dwfrm_nutritionplanner_petUserEmail']</value>
      <webElementGuid>84179164-490b-44a4-b82a-02fb61242871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
